#########################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza      #
#      SPDX-License-Identifier:  GPL-2.0-only                           #
#########################################################################
configs:
  nginx.conf:
    file: /run/configs/nginx/etc/nginx/nginx.conf
networks:
  my_network:
    driver: overlay
#   external: true
secrets:
  default.conf:
    file: /run/secrets/nginx/etc/nginx/conf.d/default.conf
services:
  nginx:
    configs:
    -
      mode: 0400
      source: nginx.conf
      target: /etc/nginx/nginx.conf
    deploy:
      placement:
        constraints:
        - node.role == worker
    image: secobau/nginx:latest
    networks:
    - my_network
    ports:
    - 80:8080
    secrets:
    -
      mode: 0400
      source: default.conf
      target: /etc/nginx/conf.d/default.conf
    volumes:
    - nginx-cache-vol:/var/cache/nginx
    - nginx-logs-vol:/var/log/nginx
    - nginx-run-vol:/var/run
version: "3.8"
volumes:
  nginx-cache-vol:
  nginx-logs-vol:
  nginx-run-vol:
#########################################################################
